select SYSTEMNAME, GMT, DATETIME, FS_DIRNAME, FS_MAX_SIZE, FS_SPACE_USED, FS_SPACE_UTIL from 
        (select SYSTEMNAME, GMT, DATETIME, FS_DIRNAME, FS_MAX_SIZE, FS_SPACE_USED, FS_SPACE_UTIL, rank() over (partition by SYSTEMNAME, FS_DIRNAME order by GMT desc) rnk from L3_FILESYSTEM a
        inner join (select SYSTEMID from GROUPS where GROUPNAME = :siebelid) b on a.SYSTEMNAME = b.SYSTEMID )
where rnk = 1 AND trunc(TO_DATE(GMT, 'DD-MM-YYYY HH24:MI:SS')) >= trunc(TO_DATE(SYSDATE-7, 'DD-MM-YYYY HH24:MI:SS')) ORDER BY SYSTEMNAME,FS_SPACE_UTIL DESC